// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYpoaRLJWKY_Ze1UUHnRa_cyr3wsviDxU',
    appId: '1:242363449102:web:52bb3354c3a1d2fa75a15f',
    messagingSenderId: '242363449102',
    projectId: 'clone-study-thread',
    authDomain: 'clone-study-thread.firebaseapp.com',
    storageBucket: 'clone-study-thread.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazyWUStntzO4PnHEWInmpSUfy89sdmmA',
    appId: '1:242363449102:android:f7d2303796891b9475a15f',
    messagingSenderId: '242363449102',
    projectId: 'clone-study-thread',
    storageBucket: 'clone-study-thread.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATV3a6kAFpptEzIR1kfiJ116ULpfvdnIw',
    appId: '1:242363449102:ios:d6dc1c9294f977a075a15f',
    messagingSenderId: '242363449102',
    projectId: 'clone-study-thread',
    storageBucket: 'clone-study-thread.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudyCh',
  );

}